### ISSUE TITLE
Errors in publiccode.yml: missing screenshots

### ISSUE THREAD

**Issue by alranel** [tdf/libreoffice-metadata#1]
The current publiccode.yml file fails to parse because the screenshots do not exist in this repository: `imgs/startcenter.png` and `imgs/writer.png`.

**Comment by deneb-alpha** [comment]
> The current publiccode.yml file fails to parse because the screenshots do not exist in this repository: `imgs/startcenter.png` and `imgs/writer.png`.

thanks for the feedback. error fixed. :)
